from tkinter import *
root = Tk()
root.geometry('400x250')
name = Label(root,text='Name')
name.place(x=30,y=50)
e1 = Entry(root)
e1.place(x=90,y=50)
e1.insert(0,'Username')
Password = Label(root,text="Address")
Password.place(x=30,y=90)
e2 = Entry(root)
e2.place(x=90,y=90)
e2.insert(0,'Password')
Contact = Label(root,text="Contact")
Contact.place(x = 30, y= 140)
e3 = Entry(root)
e3.place(x=90,y=140)
e3.insert(0,'Contact No.')
submit = Button(root,text='Submit').place(x=100,y=180)
root.mainloop()