from tkinter import *
root = Tk()
root.title('Registration'.center(80))
root.geometry('400x400')
root.resizable(0,1)
root.iconbitmap('D:\\tkinter\\c.ico')
login = Label(root,text="LOGIN")
login.pack(side=TOP)
name = Label(root,text='Name')
name.place(x=30,y=50)
e1 = Entry(root)
e1.place(x=90,y=50)
e1.insert(0,'Username')
Password = Label(root,text="Address")
Password.place(x=30,y=90)
e2 = Entry(root)
e2.place(x=90,y=90)
e2.insert(0,'Password')
Contact = Label(root,text="Email")
Contact.place(x = 30, y= 140)
e3 = Entry(root)
e3.place(x=90,y=140)
e3.insert(0,'Email')
Contact = Label(root,text="Contact")
Contact.place(x = 30, y= 180)
e3 = Entry(root)
e3.place(x=90,y=180)
e3.insert(0,'Contact No.')
Contact = Label(root,text="Age")
Contact.place(x = 30, y= 220)
e3 = Entry(root)
e3.place(x=90,y=220)
e3.insert(0,'Age')
Contact = Label(root,text="Salary")
Contact.place(x = 30, y= 260)
e3 = Entry(root)
e3.place(x=90,y=260)
e3.insert(0,'Salary')
submit = Button(root,text='Submit').place(x=100,y=300)
root.mainloop()
